name: Autotools build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install APT dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev
    - name: Install Catch2
      if: runner.os == 'Linux' && matrix.os == 'ubuntu-20.04'
      run: |
        git clone https://github.com/catchorg/Catch2.git --branch v2.13.4 --depth 1
        cd Catch2
        cmake -Bbuild -H. -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX:PATH=/usr
        sudo cmake --build build/ --target install
    - name: Install Brew dependencies
      if: runner.os == 'macOS'
      run: |
        brew install automake sdl2 catch2
    - name: Configure package
      working-directory: buildsys/autotools
      run: |
        autoreconf --install
        ./configure --prefix=$HOME/.local
    - name: Build package
      working-directory: buildsys/autotools
      run: |
        make -j 3 install
    - name: Run tests
      working-directory: buildsys/autotools
      run: |
        make check
