name: Build SCons

on:
  push:
  pull_request:
  release:
    types: [created]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        scons-options: ['ARCH=x86_64']
        experimental: [false]
        include:
          - os: 'macos-11.0'
            scons-options: 'ARCH=universal2'
            experimental: true
          - os: 'macos-10.15'
            scons-options: 'ARCH=x86_64'
            experimental: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install SCons
      run: |
        python -m pip install --upgrade pip
        python -m pip install scons
    - name: Install APT dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev
    - name: Install Brew dependencies
      if: runner.os == 'macOS'
      run: |
        brew install sdl2
    - name: Build package.
      working-directory: buildsys/scons
      env:
        SCONS_OPTIONS: ${{ matrix.scons-options }}
      run: |
        scons develop_all dist -j 3 -s CPPDEFINES=NDEBUG MODE=DEBUG_RELEASE $SCONS_OPTIONS
    - name: Archive distribution
      uses: actions/upload-artifact@v2
      with:
        name: scons-dist
        path: |
          buildsys/scons/libtcod-*.zip
          buildsys/scons/libtcod-*.tar.*
        retention-days: 3
    - name: Upload release
      if: runner.os == 'macOS' && github.event_name == 'release'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: buildsys/scons/libtcod-*.tar.*
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true
